### ISSUE TITLE
12 output TXT/binary files when running gene2vec.py

### ISSUE THREAD

**Issue by preethiperi** [jingcheng-du/Gene2vec#1]
Hi, I ran gene2vec.py on a directory containing ~7000 co-expression data sets (one for each peak from chIP-seq) and there were a total of 54 genes in these data sets. When I ran gene2vec, I saw 12 binary files and 12 text files in the output directory. Each file contains vectors of 100 features each for all 54 genes, but the vectors are different in each file. Could you please explain why there are 12 files (is it splitting up a larger file or something)?

**Comment by jingcheng-du** [comment]
The current script generates embedding at each iteration. For each iteration, it generates one binary file and one text file.
