### ISSUE TITLE
Difference between gene2vec_dim_200_iter_9.txt and gene2vec_dim_200_iter_9_w2v.txt

### ISSUE THREAD

**Issue by rvinas** [jingcheng-du/Gene2vec#3]
Dear Jingcheng,

Congratulations on the fantastic paper, it was a great read. I'd like to use the learnt gene embeddings for a downstream task and was wondering about the difference between [gene2vec_dim_200_iter_9.txt](https://github.com/jingcheng-du/Gene2vec/blob/master/pre_trained_emb/gene2vec_dim_200_iter_9.txt) and [gene2vec_dim_200_iter_9_w2v.txt](https://github.com/jingcheng-du/Gene2vec/blob/master/pre_trained_emb/gene2vec_dim_200_iter_9_w2v.txt). Which embeddings would you recommend using?

Also, are there any tissue-specific embeddings?

Best wishes,
Ramon

**Comment by jingcheng-du** [comment]
Hi Ramon, Thanks for your interests in our work. These two embeddings are same. The only difference is that the file ending with w2v.txt is in the word2vec format for python gensim package, which can be load with "gensim.models.KeyedVectors.load_word2vec_format("filename")"
